
---
title: 'The Characters: Husbands, Wives, Bosses, Workers'
author: "null"
date: '2021-11-19'
slug: []
categories: []
tags: []
description: null
toc: true
authors: []
series: []
lastmod: '2021-11-19T15:20:11-05:00'
featuredVideo: null
featuredImage: null
draft: false
---

## 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse) 
library(readxl)
library(plotly)
library(scales)
library(RColorBrewer)
contracts <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/contracts_gender_r_2.xlsx")
defs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/defs_r.xlsx")
plfs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/plfs_r.xlsx")
parties <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/parties_r.xlsx")
cites <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/cites_for_contracts.xlsx")
gendertotaltable <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/gendertotaltable.xlsx")
partnertable <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/partner_table.xlsx")

names(gendertotaltable)[1] <- "gender"
names(gendertotaltable)[5] <- "percentage"
opts <- options(knitr.kable.NA = "")

parties <- parties %>%
  full_join(cites)
names(parties)[4] <- "name"
contracts <- contracts %>%
  mutate(simplecite = cite) %>%
  mutate(simplecite = str_extract(simplecite, "[^,]+"))

names(parties)[9] <- "cite"

n_parties_joiner <- parties %>%
  group_by(cite) %>%
  count() %>%
  mutate(n_parties = n) %>%
  select(cite, n_parties)

parties <- parties %>%
  mutate(simplecite = cite) %>%
  mutate(simplecite = str_extract(simplecite, "[^,]+"))

contracts <- contracts %>%
  full_join(n_parties_joiner)

```


## Overall Gender Breakdown 

Here again is a table with general gender breakdown, with some additional information about plaintiff/defendant status. 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
gendertotaltable %>%
  knitr::kable()
```

This is the same information in bar chart form for easier visualization. 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
parties %>%
  filter(typenomf == "Man" | typenomf == "Woman") %>%
  ggplot +
  geom_bar(aes(typenomf, fill = side)) +
  scale_fill_brewer(palette = "Paired") +
  labs(title = "Gender Breakdown with π/∆ status")

```

## Marriage and Family 

```{r}
partnertable
names(partnertable) <- c("","partner","%partner","family","%family","partner+family","%p+f")
partnertable %>%
  knitr::kable()
```

## All Parties

```{r, echo = FALSE, warning = FALSE, message = FALSE}
woman_parties <- parties %>%
  filter(typenomf == "Woman") %>%
  group_by(year) %>%
  mutate(n = n()) %>%
  ggplot(aes(year,n, color = spouse, text = paste(sep = "", name,", ",side,", ",simplecite))) +
  geom_point(alpha = 0.3, size = 1.5, position = position_jitter(w = 0, h = 0.3)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "All Women as Parties") 
ggplotly(woman_parties, tooltip = "text") 

man_parties <- parties %>%
  filter(typenomf == "Man") %>%
  group_by(year) %>%
  mutate(n = n()) %>%
  ggplot(aes(year,n, color = spouse, text = paste(sep = "", name,", ",side,", ",simplecite))) +
  geom_point(alpha = 0.3, size = 1.5, position = position_jitter(w = 0, h = 0.3)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "All Men as Parties") 
ggplotly(man_parties, tooltip = "text") 
```


